services:
  mongo:
    image: mongo:7
    container_name: yeep-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - yeep_mongo_data:/data/db

volumes:
  yeep_mongo_data:
